project:
  type: website

website:
  title: "Kathleen Juarez"
  navbar:
    background: "#6a81a5"
    left:
      - href: index.qmd
        text: Home
      - href: resume-Kathleen.qmd
        text: Resume
      - href: marketing-analytics.qmd
        text: Marketing Analytics
      - href: listings-yaml-index.qmd
        text: listings/writing/blog
      - href: about.qmd
        text: About This Site
        id: about-nav-link
        
        
    
format:
  html:
    theme:
      - minty
    css: styles.css
    toc: false

editor: visual

