project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Kathleen Juarez"
  site-url: "https://kathleenjuarez.com"
  google-analytics: "G-3HP1RH107X"
  navbar:
    background: "#6a81a5"
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume/resume-Kathleen.qmd
      - text: Marketing 
        menu:
          - text: Hubspot CRM
            href: hubspot-crm-project/email-crm-project.qmd
      - text: Data Analytics
        menu:
          - text: Funnel Analysis
            href: funnel-analysis-fold/funnel-analysis.qmd
          - text: GA4 Site Analytics
            href: analytics.qmd
          - text: RevealJs Presentation
            href: funnel-analysis-fold/ao5-presentation.qmd
          # - text: Interactive Dashboard
          #  href: 
      - text: Design
        href: Design.qmd
      - text: Writing
        menu:
          - text: Long-Form
            href: longform-writing.qmd 
      - href: about.qmd
        text: About This Site
        id: about-nav-link
          
        
    
format:
  html:
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    theme:
      - minty
    css: styles.css
    toc: false

editor: visual

