project:
  type: website
  output-dir: docs

website:
  title: "Kathleen Juarez"
  site-url: "https://kathleenjuarez.com"
  navbar:
    background: "#6a81a5"
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume-Kathleen.qmd
      - text: Marketing Analytics
        href: marketing-analytics.qmd
      - text: Design
        href: Design.qmd
     # - href: Writing-test.qmd
      - text: Writing
        menu:
          - text: Sub Test 1 - Long Form
            href: subtest1.qmd
          - text: Sub Test 2
            href: subtest2.qmd
      - href: about.qmd
        text: About This Site
        id: about-nav-link
          
        
    
format:
  html:
    theme:
      - minty
    css: styles.css
    toc: false

editor: visual

